/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PskEmailInput {
        "invalidValue"?: boolean | null;
        "label"?: string | null;
        "name"?: string | null;
        "placeholder"?: string | null;
        "readOnly"?: boolean;
        "required"?: boolean;
        "value"?: string | null;
    }
}
declare global {
    interface HTMLPskEmailInputElement extends Components.PskEmailInput, HTMLStencilElement {
    }
    var HTMLPskEmailInputElement: {
        prototype: HTMLPskEmailInputElement;
        new (): HTMLPskEmailInputElement;
    };
    interface HTMLElementTagNameMap {
        "psk-email-input": HTMLPskEmailInputElement;
    }
}
declare namespace LocalJSX {
    interface PskEmailInput {
        "invalidValue"?: boolean | null;
        "label"?: string | null;
        "name"?: string | null;
        "placeholder"?: string | null;
        "readOnly"?: boolean;
        "required"?: boolean;
        "value"?: string | null;
    }
    interface IntrinsicElements {
        "psk-email-input": PskEmailInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "psk-email-input": LocalJSX.PskEmailInput & JSXBase.HTMLAttributes<HTMLPskEmailInputElement>;
        }
    }
}
